### ISSUE TITLE
Java HelloWorld 案例 | ZkeqのCoding日志

### ISSUE THREAD

**Issue by zkeq** [zkeq/Coding#139]
https://coding.maylove.pub/2021/747651b2c4dd/ 

 本节课主要学习了Java HelloWorld 案例的书写和运行

**Comment by therehello** [comment]
helloworld

**Comment by zkeq** [comment]
你好世界

**Comment by zkeq** [comment]
> @therehello
> helloworld

你好世界

**Comment by zkeq** [comment]
Java Hello world

**Comment by zkeq** [comment]
new test 评论
