### ISSUE TITLE
关于 Algolia DocSearch 申请请教

### ISSUE THREAD

**Issue by CCKNBC** [zkeq/Coding#325]
蝴蝶电报群来的
DocSearch 申请的话，请问这个域名之前是做文档的吗，因为他们不给博客申请唉，羡慕死了

**Comment by zkeq** [comment]
这域名一直都是这个博客...

我博客里面可能写了很多关于 python 的笔记？

还有就是我好像找到解决办法了，至少可以看到一点东西了

原理 DocSearch 的 Admin  Key 是在 Crawler 配置页里面的那个..

**Comment by zkeq** [comment]
我申请的时候提到的链接是这个  https://icodeq.com/categories/Python/

**Comment by CCKNBC** [comment]
> 我申请的时候提到的链接是这个 https://icodeq.com/categories/Python/

谢谢😘
